export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const SET_CURRENT_USER = "SET_CURRENT_USER";

export const GET_PROFILE = "GET_PROFILE";
export const CLEAR_CURRENT_PROFILE = "PROFILE_LOADING";
export const PROFILE_LOADING = "PROFILE_LOADING";

export const REGISTER_LOADING = "REGISTER_LOADING";
export const SET_REGISTER_SUCCESS = "SET_REGISTER_SUCCESS";
export const SET_REGISTER_ERROR = "SET_REGISTER_ERROR";
